name: wasmtime-linux-musl

on:
  push:
    tags:
      - "*"

jobs:
  wasmtime-linux-musl:
    name: wasmtime-x86_64-linux-musl
    runs-on: ubuntu-latest
    steps:

      - name: build-image
        run: |
          pushd "$(mktemp -d)"
          curl -f -L --retry 5 https://github.com/tweag/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          podman build \
            --network host \
            --pull \
            --squash \
            --tag rust:alpine-mimalloc \
            .
          popd

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build-wasmtime
        run: |
          podman run \
            --init \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace/wasmtime \
            --workdir /workspace/wasmtime \
            rust:alpine-mimalloc \
            cargo build \
            --release \
            --bin wasmtime \
            --all-features \
            --config 'profile.release.lto = "thin"'

      - name: test-wasmtime
        run: |
          MIMALLOC_VERBOSE=1 target/release/wasmtime --version
          file target/release/wasmtime

      - name: package-wasmtime
        run: |
          mkdir wasmtime-v14.0.0-x86_64-linux-musl
          mv target/release/wasmtime wasmtime-v14.0.0-x86_64-linux-musl
          XZ_OPT="-T0 -9" \
            tar \
            --sort=name \
            --mtime=1970-01-01T00:00:00Z \
            --owner=0 \
            --group=0 \
            --numeric-owner \
            -cJf wasmtime-v14.0.0-x86_64-linux-musl.tar.xz wasmtime-v14.0.0-x86_64-linux-musl

      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasmtime-x86_64-linux-musl
          path: wasmtime-v14.0.0-x86_64-linux-musl.tar.xz
