name: musl

on:
  push:

jobs:
  musl:
    name: wasmtime-x86_64-linux-musl
    runs-on: ubuntu-latest
    steps:

      - name: deps
        run: |
          sudo apt install -y \
            musl-tools
          rustup target add x86_64-unknown-linux-musl

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build
        run: |
          cargo build \
            --target x86_64-unknown-linux-musl \
            --release \
            --bin wasmtime \
            --all-features \
            --config 'profile.release.lto = "thin"' \
            --config 'profile.release.strip = "symbols"'

          mkdir wasmtime-v9.0.3-x86_64-linux-musl
          mv target/x86_64-unknown-linux-musl/release/wasmtime wasmtime-v9.0.3-x86_64-linux-musl
          XZ_OPT=-9 \
            tar \
            --sort=name \
            --mtime=1970-01-01T00:00:00Z \
            --owner=0 \
            --group=0 \
            --numeric-owner \
            -cJf wasmtime-v9.0.3-x86_64-linux-musl.tar.xz wasmtime-v9.0.3-x86_64-linux-musl

      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasmtime-x86_64-linux-musl
          path: wasmtime-v9.0.3-x86_64-linux-musl.tar.xz
